### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by laurentheirendt** [elixir-luxembourg/DS-DM-training#4]

**Comment by vildead** [comment]
Just to check. 
we should go for `cc-by-4.0`, right? (or cc-by-sa-4.0?) 
@pinarpink  Thank you for any input ! 

In any case, we should include a description of how to cite the training...

**Comment by pinarpink** [comment]
Hi Vilem 
[cc by attribution](https://creativecommons.org/licenses/by/4.0/legalcode )
 looks ok to me.
